name: Helm Chart Push

on:
  push:
    branches:
      - part4

jobs:
  package-and-push-chart:
    runs-on: ubuntu-latest
    env:
      AZURE_CONTAINER_NAME: helm
      AZURE_ACCOUNT_NAME: devopsassessmenthelmrepo
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Package Helm Chart
      run: |
        helm package ./part-2/list-chart 
        
    - name: Push and Update Helm Repo Index
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az storage blob upload -c $AZURE_CONTAINER_NAME --account-name $AZURE_ACCOUNT_NAME -f ./list-chart-0.1.0.tgz -n list-chart-0.1.0.tgz
          az storage blob download --container-name $AZURE_CONTAINER_NAME --name index.yaml --file ./index.yaml --account-name $AZURE_ACCOUNT_NAME
          helm repo index . --merge ./index.yaml
          az storage blob upload --container-name $AZURE_CONTAINER_NAME --name index.yaml --file ./index.yaml --account-name $AZURE_ACCOUNT_NAME